//
// Created by Hodosi on 3/5/2021.
//

#ifndef IMMOBILEADMINISTRATOR_REPOSITORY_H
#define IMMOBILEADMINISTRATOR_REPOSITORY_H

#include "../domain/valueObject.h"

#endif //IMMOBILEADMINISTRATOR_REPOSITORY_H
