//
// Created by Hodosi on 3/5/2021.
//

#ifndef IMMOBILEADMINISTRATOR_USERINTERFACE_H
#define IMMOBILEADMINISTRATOR_USERINTERFACE_H

void userInterface();

#endif //IMMOBILEADMINISTRATOR_USERINTERFACE_H
